[build]
target = "index.html"
dist = "dist"

[serve]
addresses = ["127.0.0.1"]
port = 3000
reload = true
open = true

[[proxy]]
rewrite = "/api"
backend = "http://127.0.0.1:8080/api"

[tools.wasm_opt]
args = ["-O", "--enable-bulk-memory"]
